- README.md
- lua/spelunk/config.lua
- lua/spelunk/init.lua
- lua/spelunk/telescope.lua
- lua/spelunk/ui.lua
- lua/telescope/_extensions/spelunk.lua
This PR adds the ability to fuzzy-find over bookmarks - both all given bookmarks, as well as bookmarks in the current stack. This is done via Telescope integration. Also took the opportunity to clean up other things as I went. Meaningfully, regular preview filetypes are being set now, so syntax highlighting should work.
> Add telescope integration

- .luarc.json
- README.md
- faqs/format_filenames.md
- lua/spelunk/init.lua
- lua/spelunk/telescope.lua
Provides a solution to the main issue in https://github.com/EvWilson/spelunk.nvim/issues/10. Complete with documentation, with new `faqs/` folder. Also, add a LuaLS config to get better code intelligence (just Mac Homebrew config for now).
> (feat) Add ability to format display of filenames

- README.md
- lua/spelunk/init.lua
- lua/spelunk/telescope.lua
- lua/spelunk/types.lua
- lua/spelunk/util.lua
Intended as an enabling effort for https://github.com/EvWilson/spelunk.nvim/issues/13, this exposes information about the internal bookmark state for people wanting to create a version of the Telescope integration through other means.
> (refactor) Expose stack information in case others want to build search experiences

- lua/spelunk/init.lua
Addressing https://github.com/EvWilson/spelunk.nvim/issues/14
> (fix) Reject empty stack names

- README.md
- lua/spelunk/config.lua
- lua/spelunk/init.lua
- lua/spelunk/layout.lua
- lua/spelunk/types.lua
- lua/spelunk/ui.lua
This should help to provide more context in projects with longer file names (hello, JVM).
Also cleared up a couple smaller misbehaviors raised in recent issues.
> Add a horizontal layout option

- README.md
- lua/spelunk/config.lua
- lua/spelunk/init.lua
- lua/spelunk/mark.lua
Addresses feature request in https://github.com/EvWilson/spelunk.nvim/issues/22
> Added status column display for mark indices

- README.md
- lua/spelunk/config.lua
- lua/spelunk/init.lua
- lua/spelunk/ui.lua
Should address https://github.com/EvWilson/spelunk.nvim/issues/25
> Add ability to skip setting keybinds for given actions

- README.md
- lua/spelunk/layout.lua
- lua/spelunk/types.lua
Should address the ask in https://github.com/EvWilson/spelunk.nvim/issues/24
> Add ability to provide your own LayoutProvider

- README.md
- lua/spelunk/config.lua
- lua/spelunk/init.lua
- lua/spelunk/telescope.lua
- lua/telescope/_extensions/spelunk.lua
Should address ask in https://github.com/EvWilson/spelunk.nvim/issues/23, as well as one from an earlier PR.
> Fuzzy find stacks, and add marks to quickfix list

- lua/spelunk/init.lua
- lua/spelunk/mark.lua
- lua/spelunk/ui.lua
- lua/spelunk/util.lua
Should address some of the core concerns in: https://github.com/EvWilson/spelunk.nvim/issues/31
Two things:
- Regression introduced from virtual mark work done in: https://github.com/EvWilson/spelunk.nvim/pull/26
- Did not properly handle missing previously marked files
> Improve safety in persistence layer and preview

- lua/spelunk/init.lua
- lua/spelunk/mark.lua
- lua/spelunk/types.lua
Seeking to address the latter portions of: https://github.com/EvWilson/spelunk.nvim/issues/32
> Recreate deleted buffers for marked locations

- lua/spelunk/init.lua
Seeking to address issue in: https://github.com/EvWilson/spelunk.nvim/issues/38
> Disallow navigating to a missing file

- README.md
- faqs/display_treesitter_context.md
- lua/spelunk/init.lua
- lua/spelunk/telescope.lua
- lua/spelunk/types.lua
- lua/spelunk/util.lua
Seeks to address: https://github.com/EvWilson/spelunk.nvim/issues/39
> Add context Treesitter display support

- lua/spelunk/init.lua
Seeking to address: https://github.com/EvWilson/spelunk.nvim/issues/40
> Try deferring startup work to not block LSP server attach

- README.md
- faqs/add_and_show_mark_metadata.md
- faqs/hide_preview.md
- lua/spelunk/init.lua
- lua/spelunk/mark.lua
- lua/spelunk/persistence.lua
- lua/spelunk/types.lua
- lua/spelunk/util.lua
Seeks to address: https://github.com/EvWilson/spelunk.nvim/issues/35
Implemented in a more generic fashion to allow for other use cases as folks see fit.
Also, cleaned up some other documentation and some style consistency.
> Mark metadata - allow for aliases in display

- lua/spelunk/mark.lua
Seeks to address: https://github.com/EvWilson/spelunk.nvim/issues/47
> Add missing line in recovery logic

- lua/spelunk/init.lua
Seeks to address: https://github.com/EvWilson/spelunk.nvim/issues/49
> Fix searching current stack by adding stack name to entries

- lua/spelunk/init.lua
Seeks to address: https://github.com/EvWilson/spelunk.nvim/issues/50
> Return cursor to previous window when moving to marked location

- lua/spelunk/init.lua
- lua/spelunk/ui.lua
Second stab at addressing: https://github.com/EvWilson/spelunk.nvim/issues/50
> Fixing cursor window return, part 2

- README.md
- lua/spelunk/config.lua
Seeks to address: https://github.com/EvWilson/spelunk.nvim/issues/56
> Allow for setting keybinds to an array of strings

- lua/spelunk/init.lua
Seeks to address: https://github.com/EvWilson/spelunk.nvim/issues/58
> Disallow searching when the UI is open
